var keyPlaceIconMap = new HashMap();
keyPlaceIconMap.put("001", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-school.png");
keyPlaceIconMap.put("002", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-clinic.png");
keyPlaceIconMap.put("003", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-shop.png");
keyPlaceIconMap.put("004", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-sestaurant.png");
keyPlaceIconMap.put("005", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-hotel.png");
keyPlaceIconMap.put("006", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-amusement.png");
keyPlaceIconMap.put("007", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-Internet cafe.png");
keyPlaceIconMap.put("008", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-shower.png");
keyPlaceIconMap.put("009", uiDomain + "/web-assets/common/images/iconclass/iconbox/special/region-workshop.png");
