var keyPlaceIconMap = new HashMap();
keyPlaceIconMap.put("keyPlaceIcon101", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_101.png");// 宾馆
keyPlaceIconMap.put("keyPlaceIcon102", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_102.png");// 酒店
keyPlaceIconMap.put("keyPlaceIcon103", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_103.png");// 饭店
keyPlaceIconMap.put("keyPlaceIcon202", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_202.png");// 桑拿
keyPlaceIconMap.put("keyPlaceIcon203", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_203.png");// 沐足
keyPlaceIconMap.put("keyPlaceIcon204", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_204.png");// 按摩场所
keyPlaceIconMap.put("keyPlaceIcon301", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_301.png");// 理发店、美发店
keyPlaceIconMap.put("keyPlaceIcon401", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_401.png");// 游泳场馆
keyPlaceIconMap.put("keyPlaceIcon503", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_503.png");// 卡拉OK厅
keyPlaceIconMap.put("keyPlaceIcon504", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_504.png");// 影剧院
keyPlaceIconMap.put("keyPlaceIcon507", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_507.png");// 网吧
keyPlaceIconMap.put("keyPlaceIcon509", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_509.png");// 夜总会
keyPlaceIconMap.put("keyPlaceIcon701", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_701.png");// 餐城（吧）
keyPlaceIconMap.put("keyPlaceIcon801", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_801.png");// 商厅
keyPlaceIconMap.put("keyPlaceIcon704", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_704.png");// 酒场（店）
keyPlaceIconMap.put("keyPlaceIcon905", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_905.png");// 学校
keyPlaceIconMap.put("keyPlaceIcon1001", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_1001.png");// 候车室（汽车站）
keyPlaceIconMap.put("keyPlaceIcon1108", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_1108.png");// 银行
keyPlaceIconMap.put("keyPlaceIcon1202", uiDomain + "/images/map/gisv0/map_config/unselected/keyplace/icon_1202.png");// 加油站
